[TSS]
TURRETS = [
  'GCLHZ7NZVBPS2UYKE47LZQUC2OGHIYB34Q67RG2MMTFLS7EAWQRZXFRV', # self
  'GD6K7DYP6H5EQKXEOVXWDCRKQJSV55UWFSTTN4CNA6YT74FBDKJTQHMB', # tss1
  'GAV3MJ6R2N5S43W6O724M3PWUZYMNR3J3W5QS3H4VQZWZDX6TZRURORD', # tss2
]